name: Publish Mod to Steam Workshop

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Steam Workshop
        uses: m00nl1ght-dev/steam-workshop-deploy@main
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          path: .
          appId: 294100
          publishedFileId: 3736994429